cols_conversion_dict = {'team_id': 'team_id',
 'mutation: effective date (dd-mm-yyyy)': 'mutation_date',
 'insert_date': 'insert_date',
 'name val.report': 'val_report_name',
 'val.report, approved by kam, operational date (dd-mm-yyyy)': 'val_report_date',
 'plan nvwa, concerning year (only for vmpr data)': 'plan_nvwa_year',
 'groupori': 'groupori',
 'use': 'use',
 'product group': 'productgroup',
 'sample matrix (desc_code) (= waarsoort)': 'sample_matrix',
 'e02_sampmatcode1_en': 'e02_sampmatcode1_en',
 'e02_sampmatcode1_nl': 'e02_sampmatcode1_nl',
 'e02_sampmatcode2_en': 'e02_sampmatcode2_en',
 'e02_sampmatcode2_nl': 'e02_sampmatcode2_nl',
 'e02_sampmatcode3_en': 'e02_sampmatcode3_en',
 'e02_sampmatcode3_nl': 'e02_sampmatcode3_nl',
 'e02_sampmatcode4_en': 'e02_sampmatcode4_en',
 'e02_sampmatcode4_nl': 'e02_sampmatcode4_nl',
 'product/matrix code': 'productmatrix_code',
 'mtx_code': 'mtx_code',
 'substance group': 'substance_group',
 'antibiotica_ab_groep': 'antibiotica_ab_groep',
 'param_code': 'param_code',
 'param_name': 'param_name',
 'paramtext_lims': 'paramtext_lims',
 'paramtext_abbreviation': 'paramtext_abbreviation',
 'paramtype_code': 'paramtype_code',
 'paramtype_name': 'paramtype_name',
 'anmethodref': 'anmethodref',
 'anmethodref_new': 'anmethodref_new',
 'flex_scope_no': 'flex_scope_no',
 'qual/quan method': 'qual_quan_method',
 'anlytyp_code': 'anlytyp_code',
 'anlytyp_name': 'anlytyp_name',
 'anlymd_code': 'anlymd_code',
 'anlymd_name': 'anlymd_name',
 'mdacc_code': 'mdacc_code',
 'mdacc_name': 'mdacc_name',
 'resinfo': 'resinfo',
 'resunit_wfsr': 'resunit_wfsr',
 'unit_code': 'unit_code',
 'exprres_code': 'exprres_code',
 'lod': 'lod',
 'loq': 'loq',
 'ccalpha': 'ccalpha',
 'ccbeta': 'ccbeta',
 'resvaluncert (%)': 'resvaluncert',
 'evallowlimit': 'evallowlimit',
 'action level (in case of screening)': 'actionlevel',
 'lmttyp_code': 'lmttyp_code',
 'lmttyp_name': 'lmttyp_name',
 'if screening sop, what is confirmation sop?': 'confirmation_sop',
 'lu_s_productid (only for np residues)': 'lu_s_productid',
 'matrix_cal_curve': 'matrix_cal_curve',
 'measuring_range': 'measuring_range',
 'trueness j / recovery (%)': 'trueness_j_recovery',
 'rsdr (%)': 'rsdr',
 'rsdwR / rsdRL (%)': 'rsdwr_rsdrl',
 'remarks': 'remarks'}